<?php

namespace Pro3x\InvoiceBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-11-25 at 15:54:53.
 */
class CustomerControllerTest extends WebTestCase
{
	private $client;
	
	/**
	 * 
	 * @return \Symfony\Bundle\FrameworkBundle\Client
	 */
	public function getClient()
	{
		return $this->client;
	}

	public function setClient($client)
	{
		$this->client = $client;
	}

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$client = static::createClient();
		$client->followRedirects();
		$crawler = $client->request('get', '/admin');
		
		$form = $crawler->selectButton('Login')->form(array(
			'_username' => 'aco',
			'_password' => 'login'
		));
		
		$crawler = $client->submit($form);
		$this->assertTrue($crawler->filter('html:contains("Pro3x Business Dashboard")')->count() == 1);
		
		$this->setClient($client);
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
		
	}

	/**
	 * @covers Pro3x\InvoiceBundle\Controller\CustomerController::addAction
	 * @todo   Implement testAddAction().
	 */
	public function testAddAction()
	{
		$client = $this->getClient();
		
		$crawler = $client->request('get', '/admin/customers/add'); /* @var $crawler \Symfony\Component\DomCrawler\Crawler */
		$count = $crawler->filter('html:contains("New Customer")')->count();
		
		$this->assertTrue($count == 1);
		
		$form = $crawler->selectButton('Save')->form(array(
			'pro3x_invoicebundle_customertype[name]' => 'Mick Jagger'
		), 'post');

		$crawler = $client->submit($form);
		$count = $crawler->filter('html:contains("New customer created successfully")')->count();
		$this->assertTrue($count == 1, $client->getResponse()->getContent());
	}

	/**
	 * @covers Pro3x\InvoiceBundle\Controller\CustomerController::editAction
	 * @todo   Implement testEditAction().
	 */
	public function testEditAction()
	{
		$client = $this->getClient();
		
		$crawler = $client->request('get', '/admin/customers');
		$this->assertTrue($crawler->filter('html:contains("Customers")')->count() == 1);
		
		$link = $crawler->selectLink('Edit')->link();
		$crawler = $client->click($link);
		
		$this->assertTrue($crawler->filter('html:contains("Edit Customer")')->count() == 1);
		$form = $crawler->selectButton('Save')->form();
		
		$crawler = $client->submit($form);
		$this->assertTrue($crawler->filter('html:contains("Customers")')->count() == 1);
	}

	/**
	 * @covers Pro3x\InvoiceBundle\Controller\CustomerController::indexAction
	 * @todo   Implement testIndexAction().
	 */
	public function testIndexAction()
	{
		$client = $this->getClient();
		$crawler = $client->request('get', '/admin/customers');
		$this->assertTrue($crawler->filter('html:contains("Customers")')->count() == 1);
		
		$editCount = $crawler->selectLink('Edit')->count();
		$noDataCount = $crawler->filter('No records found')->count();
		
		$this->assertTrue($editCount > 0 || $noDataCount == 1);
	}

}
