<?php

namespace Pro3x\WarehouseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReceiptRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReceiptRepository extends EntityRepository
{
	
	
	
}
