<?php

namespace Pro3x\InvoiceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends EntityRepository
{
	public function getCount()
	{
		return $this->createQueryBuilder('c')->select('count(c)')->getQuery()->getSingleScalarResult();
	}
}
