<?php

namespace Pro3x\InvoiceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DailySalesReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DailySalesReportRepository extends EntityRepository
{
}
