<?php

namespace Pro3x\InvoiceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InvoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceRepository extends EntityRepository
{
	public function count()
	{
		return $this->createQueryBuilder('c')->select('count(c)')->getQuery()->getSingleScalarResult();
	}
	
	public function countByUser($userId)
	{
		return $this->createQueryBuilder('c')->select('count(c)')->where('c.user = :userId')->setParameter('userId', $userId)->getQuery()->getSingleScalarResult();
	}
}
