<?php

namespace Pro3x\InvoiceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TaxRateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
	public function count()
	{
		return $this->createQueryBuilder('c')->select('count(c)')->getQuery()->getSingleScalarResult();
	}
	
	public function search($code)
	{
		return $this->createQueryBuilder('c')
				->where('c.name LIKE :query OR c.barcode LIKE :query OR c.code LIKE :query')
				->orderBy('c.name', 'ASC')
				->setParameter('query', "%$code%")
				->getQuery()->getResult();
	}
}
