<?php

namespace Pro3x\SecurityBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-11-12 at 12:27:45.
 */
class DefaultControllerTest extends WebTestCase
{

	/**
	 * @covers Pro3x\SecurityBundle\Controller\DefaultController::indexAction
	 * @todo   Implement testIndexAction().
	 */
	public function testIndexAction()
	{
		$client = static::createClient();

        $crawler = $client->request('GET', '/hello/Fabien');

        $this->assertTrue($crawler->filter('html:contains("Hello Fabien")')->count() > 0);
	}

}
